"""updated models

Revision ID: 5b89657db203
Revises: 45aee5852c3d
Create Date: 2026-06-06 18:01:46.819888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b89657db203'
down_revision = '45aee5852c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.alter_column('featured_type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('image_variants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_variants_image'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'images', ['image_id'], ['id'])

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_images_blog'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'blogs', ['blog_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_images_blog'), 'blogs', ['blog_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('image_variants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_variants_image'), 'images', ['image_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.alter_column('featured_type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
